# Generated by Django 5.0.3 on 2024-07-16 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Metafield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('key', models.CharField(max_length=64)),
                ('namespace', models.CharField(max_length=255)),
                ('owner_id', models.BigIntegerField()),
                ('owner_resource', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('namespace', 'key', 'owner_id', 'owner_resource')},
            },
        ),
    ]
